/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.GUIBan.GUIBan;
import GUI.ThongKe.GUIHoaDon;
import DTO.Account;
import GUI.Panel.DanhSachMonAn.GUIMon;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DucThanh
 */
public class GUIHome extends javax.swing.JFrame {

    /**
     * Creates new form Home2
     */
    Account userConn;
    boolean isOrder, isAccount, isMon, isNhanvien, isThongke = false;

    public GUIHome(Account userConn) {
        initComponents();
        this.setSize(panelBoxFunction.getWidth() + 5, this.getHeight());
        this.setLocationRelativeTo(null);

        this.setIconImage(new ImageIcon("icon/icon_logo.png").getImage());

        panelBoxFunction.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 20));

        labelBackground.setIcon(initBackground());
        this.userConn = userConn;
        labelLogout.setText(userConn.getUserName());
        isActivePanelAccount(userConn.getPermission());
    }

    public ImageIcon initBackground() {
        ImageIcon background = new ImageIcon("C:\\Users\\DucThanh\\OneDrive\\Documents\\NetBeansProjects\\doAnJava\\Img\\Background.jpg");

        Image image = background.getImage();
        image = image.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(image);
    }

    private void isActivePanelAccount(int permission) {
        switch (permission) {
            case 0: {
                isOrder = isAccount = isMon = isNhanvien = isThongke = true;
                break;
            }

            case 1: {
                isOrder = isMon = isNhanvien = isThongke = true;
                panelAccount.setBackground(new Color(102,102,102));
                break;
            }
            case 2: {
                isOrder = true;
                panelAccount.setBackground(new Color(102,102,102));
                panelMon.setBackground(new Color(102,102,102));
                panelNhanvien.setBackground(new Color(102,102,102));
                panelThongke.setBackground(new Color(102,102,102));
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBoxFunction = new javax.swing.JPanel();
        panelOrder = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelAccount = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelMon = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelNhanvien = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelThongke = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        labelLogout = new javax.swing.JLabel();
        panelClose = new javax.swing.JPanel();
        labelClose = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setPreferredSize(new java.awt.Dimension(1370, 758));

        panelBoxFunction.setBackground(new java.awt.Color(204, 153, 0));

        panelOrder.setAlignmentX(1.0F);
        panelOrder.setAlignmentY(1.0F);
        panelOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOrderMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/orderIcon.png"))); // NOI18N
        jLabel1.setText("Order");

        javax.swing.GroupLayout panelOrderLayout = new javax.swing.GroupLayout(panelOrder);
        panelOrder.setLayout(panelOrderLayout);
        panelOrderLayout.setHorizontalGroup(
            panelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );
        panelOrderLayout.setVerticalGroup(
            panelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        panelBoxFunction.add(panelOrder);

        panelAccount.setAlignmentX(1.0F);
        panelAccount.setAlignmentY(1.0F);
        panelAccount.setPreferredSize(new java.awt.Dimension(154, 68));
        panelAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAccountMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/listIcon.png"))); // NOI18N
        jLabel2.setText("Account");

        javax.swing.GroupLayout panelAccountLayout = new javax.swing.GroupLayout(panelAccount);
        panelAccount.setLayout(panelAccountLayout);
        panelAccountLayout.setHorizontalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );
        panelAccountLayout.setVerticalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        panelBoxFunction.add(panelAccount);

        panelMon.setAlignmentX(1.0F);
        panelMon.setAlignmentY(1.0F);
        panelMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMonMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/foodIcon.png"))); // NOI18N
        jLabel3.setText("Món");

        javax.swing.GroupLayout panelMonLayout = new javax.swing.GroupLayout(panelMon);
        panelMon.setLayout(panelMonLayout);
        panelMonLayout.setHorizontalGroup(
            panelMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelMonLayout.setVerticalGroup(
            panelMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        panelBoxFunction.add(panelMon);

        panelNhanvien.setAlignmentX(1.0F);
        panelNhanvien.setAlignmentY(1.0F);
        panelNhanvien.setPreferredSize(new java.awt.Dimension(180, 68));
        panelNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelNhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelNhanvienMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nhanVienIcon.png"))); // NOI18N
        jLabel4.setText("Nhân viên");

        javax.swing.GroupLayout panelNhanvienLayout = new javax.swing.GroupLayout(panelNhanvien);
        panelNhanvien.setLayout(panelNhanvienLayout);
        panelNhanvienLayout.setHorizontalGroup(
            panelNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhanvienLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        panelNhanvienLayout.setVerticalGroup(
            panelNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        panelBoxFunction.add(panelNhanvien);

        panelThongke.setAlignmentX(1.0F);
        panelThongke.setAlignmentY(1.0F);
        panelThongke.setPreferredSize(new java.awt.Dimension(170, 68));
        panelThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelThongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelThongkeMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongkeIcon.png"))); // NOI18N
        jLabel5.setText("Thống Kê");

        javax.swing.GroupLayout panelThongkeLayout = new javax.swing.GroupLayout(panelThongke);
        panelThongke.setLayout(panelThongkeLayout);
        panelThongkeLayout.setHorizontalGroup(
            panelThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        panelThongkeLayout.setVerticalGroup(
            panelThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelBoxFunction.add(panelThongke);

        panelLogout.setAlignmentX(1.0F);
        panelLogout.setAlignmentY(1.0F);
        panelLogout.setPreferredSize(new java.awt.Dimension(154, 68));
        panelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLogoutMouseExited(evt);
            }
        });

        labelLogout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/LogoutIcon.png"))); // NOI18N
        labelLogout.setText("Logout");

        javax.swing.GroupLayout panelLogoutLayout = new javax.swing.GroupLayout(panelLogout);
        panelLogout.setLayout(panelLogoutLayout);
        panelLogoutLayout.setHorizontalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );
        panelLogoutLayout.setVerticalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        panelBoxFunction.add(panelLogout);

        panelClose.setAlignmentX(1.0F);
        panelClose.setAlignmentY(1.0F);
        panelClose.setPreferredSize(new java.awt.Dimension(154, 70));
        panelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCloseMouseExited(evt);
            }
        });

        labelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close-icon.png"))); // NOI18N
        labelClose.setText("Close");

        javax.swing.GroupLayout panelCloseLayout = new javax.swing.GroupLayout(panelClose);
        panelClose.setLayout(panelCloseLayout);
        panelCloseLayout.setHorizontalGroup(
            panelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelClose, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );
        panelCloseLayout.setVerticalGroup(
            panelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelClose, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelBoxFunction.add(panelClose);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        labelBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(labelBackground, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
            .addComponent(panelBoxFunction, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelBoxFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOrderMouseClicked
        // TODO add your handling code here:
        if (isOrder) {
            GUIBan order = new GUIBan(userConn);
            order.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_panelOrderMouseClicked

    private void panelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_panelCloseMouseClicked

    private void panelThongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelThongkeMouseClicked
        // TODO add your handling code here:
        if(isThongke)
        {
            GUIHoaDon thongke = new GUIHoaDon();
            thongke.setVisible(true);
        }
        
    }//GEN-LAST:event_panelThongkeMouseClicked

    private void panelMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMonMouseClicked
        // TODO add your handling code here:
        if(isMon)
        {
            GUIMon danhsachmon = new GUIMon();
            danhsachmon.setVisible(true);
        }
        
    }//GEN-LAST:event_panelMonMouseClicked

    private void panelAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAccountMouseClicked
        // TODO add your handling code here:
        if (isAccount) {
            GUIAccount guiAccount = new GUIAccount();
            guiAccount.setVisible(true);
        }

    }//GEN-LAST:event_panelAccountMouseClicked

    private void panelNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNhanvienMouseClicked
        // TODO add your handling code here:
        if(isNhanvien)
        {
            GUINhanVien danhsachnhanvien = new GUINhanVien();
            danhsachnhanvien.setVisible(true);
        }
    }//GEN-LAST:event_panelNhanvienMouseClicked

    private void panelOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOrderMouseEntered
        // TODO add your handling code here:
        if(isOrder)
        {
            panelOrder.setBackground(Color.white);
        }
        
    }//GEN-LAST:event_panelOrderMouseEntered

    private void panelOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOrderMouseExited
        // TODO add your handling code here:
        if(isOrder)
        panelOrder.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_panelOrderMouseExited

    private void panelAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAccountMouseEntered
        // TODO add your handling code here:
        if(isAccount)
        panelAccount.setBackground(Color.white);
    }//GEN-LAST:event_panelAccountMouseEntered

    private void panelAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAccountMouseExited
        // TODO add your handling code here:
        if(isAccount)
        panelAccount.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_panelAccountMouseExited

    private void panelMonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMonMouseEntered
        // TODO add your handling code here:
        if(isMon)
        panelMon.setBackground(Color.white);
    }//GEN-LAST:event_panelMonMouseEntered

    private void panelNhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNhanvienMouseEntered
        // TODO add your handling code here:
        if(isNhanvien)
        panelNhanvien.setBackground(Color.white);
    }//GEN-LAST:event_panelNhanvienMouseEntered

    private void panelThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelThongkeMouseEntered
        // TODO add your handling code here:
        if(isThongke)
        panelThongke.setBackground(Color.white);
    }//GEN-LAST:event_panelThongkeMouseEntered

    private void panelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseEntered
        // TODO add your handling code here:
        panelLogout.setBackground(Color.white);
    }//GEN-LAST:event_panelLogoutMouseEntered

    private void panelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCloseMouseEntered
        // TODO add your handling code here:
        panelClose.setBackground(Color.white);
    }//GEN-LAST:event_panelCloseMouseEntered

    private void panelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCloseMouseExited
        // TODO add your handling code here:
        panelClose.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_panelCloseMouseExited

    private void panelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseExited
        // TODO add your handling code here:
        panelLogout.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_panelLogoutMouseExited

    private void panelThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelThongkeMouseExited
        // TODO add your handling code here:
        if(isThongke)
        panelThongke.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_panelThongkeMouseExited

    private void panelNhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNhanvienMouseExited
        // TODO add your handling code here:
        if(isNhanvien)
        panelNhanvien.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_panelNhanvienMouseExited

    private void panelMonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMonMouseExited
        // TODO add your handling code here:
        if(isMon)
        panelMon.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_panelMonMouseExited

    private void panelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseClicked
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Đăng Xuất!");
        if (check == JOptionPane.YES_OPTION) {
            GUILogin login = new GUILogin();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_panelLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIHome(new Account()).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelClose;
    private javax.swing.JLabel labelLogout;
    private javax.swing.JPanel panelAccount;
    private javax.swing.JPanel panelBoxFunction;
    private javax.swing.JPanel panelClose;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelMon;
    private javax.swing.JPanel panelNhanvien;
    private javax.swing.JPanel panelOrder;
    private javax.swing.JPanel panelThongke;
    // End of variables declaration//GEN-END:variables
}
