/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panel;

import DAL.DALMon;
import GUI.Panel.DanhSachMonAn.FormFixMon;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author DucThanh
 */
public class PanelMon extends javax.swing.JPanel {

    /**
     * Creates new form PanelMon
     */
    public PanelMon() {
        initComponents();
    }

    public void setVisibleButtonSua(boolean status) {
        btnSua.setVisible(status);
    }

    public void hideSoLuong() {
        spSoLuong.setVisible(false);
    }

    public void setName(String name) {
        labelName.setText(name);
    }

    public void setGia(float gia) {
        labelGia.setText(gia + "");
    }

    public void setImgMon(String url) {
        
        if (new DALMon().getMonByTen(labelName.getText()).isTrangThai() == false) {
            ImageIcon icon = new ImageIcon("C:\\Users\\DucThanh\\OneDrive\\Documents\\NetBeansProjects\\doAnJava\\src\\icon\\monngungban.png");
            labelImage.setIcon(icon);
        } else {
            ImageIcon icon = new ImageIcon(url);
            Image image = icon.getImage();
            image = image.getScaledInstance((int) labelImage.getPreferredSize().getWidth(), (int) labelImage.getPreferredSize().getHeight(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(image);
            labelImage.setIcon(icon);
        }

    }

    public int getCount() {
        return (int) spSoLuong.getValue();
    }

    public void resetCount() {
        spSoLuong.setValue(0);
    }

    public String getTenMon() {
        return labelName.getText();
    }

    public float getGia() {
        return Float.parseFloat(labelGia.getText());
    }

    public void setSizePaelMon(int width, int height) {
        this.setPreferredSize(new Dimension(width, height));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBoxContent = new javax.swing.JPanel();
        labelGia = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        spSoLuong = new javax.swing.JSpinner();
        btnSua = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panelBoxContent.setBackground(new java.awt.Color(255, 255, 255));

        labelGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelGia.setText("100000");

        labelName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelName.setText("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");

        spSoLuong.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spSoLuong.setMinimumSize(new java.awt.Dimension(0, 0));
        spSoLuong.setPreferredSize(new java.awt.Dimension(40, 30));

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBoxContentLayout = new javax.swing.GroupLayout(panelBoxContent);
        panelBoxContent.setLayout(panelBoxContentLayout);
        panelBoxContentLayout.setHorizontalGroup(
            panelBoxContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoxContentLayout.createSequentialGroup()
                .addGroup(panelBoxContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBoxContentLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelGia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBoxContentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBoxContentLayout.setVerticalGroup(
            panelBoxContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoxContentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBoxContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBoxContentLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(labelGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBoxContentLayout.createSequentialGroup()
                        .addGroup(panelBoxContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 180));

        labelImage.setBackground(new java.awt.Color(255, 255, 255));
        labelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/monngungban.png"))); // NOI18N
        labelImage.setMaximumSize(new java.awt.Dimension(1000, 1000));
        labelImage.setMinimumSize(new java.awt.Dimension(400, 300));
        labelImage.setPreferredSize(new java.awt.Dimension(200, 180));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBoxContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
            .addComponent(panelBoxContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        FormFixMon fixMon = new FormFixMon(new DALMon().getMonByTen(labelName.getText()), this);
        fixMon.setVisible(true);
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelGia;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelName;
    private javax.swing.JPanel panelBoxContent;
    private javax.swing.JSpinner spSoLuong;
    // End of variables declaration//GEN-END:variables
}
