
package GUI.Panel;

import GUI.GUIBan.GUIBan;
import java.awt.Color;

/**
 *
 * @author DucThanh
 */
public class PanelBan extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private GUIBan show;
    public PanelBan(GUIBan show) {
        initComponents();
        this.show = show;
        System.out.println(this.getWidth());
    }
    public void setText(String text)
    {
        labelBan.setText(text);
    }
    public int getBanPosition()
    {
        return Integer.parseInt(labelBan.getText().substring(labelBan.getText().indexOf(" ")+1));
    }
    public void setColor(boolean status)
    {
        if(status==true)
        {
            this.setBackground(new Color(204,153,0));
        }
        else
        {
            this.setBackground(new Color(244,255,2));
        }
    }
    @Override
    public String toString()
    {
        return "Ban: " + labelBan.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 255, 2));
        setPreferredSize(new java.awt.Dimension(120, 120));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        labelBan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tableIcon.png"))); // NOI18N
        labelBan.setText("Bàn 1");
        labelBan.setPreferredSize(new java.awt.Dimension(120, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        int banSo = Integer.parseInt(labelBan.getText().substring(labelBan.getText().indexOf(" ")+1));
        show.setBanCurrent(banSo);
        show.showBil(banSo);
        show.showBillGoiThem(banSo);
        show.showTongBill(banSo);
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        labelBan.setForeground(Color.white);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        labelBan.setForeground(Color.black);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelBan;
    // End of variables declaration//GEN-END:variables
}
